version: '3.8'

services:
  rsyslog:
    build: ./rsyslog
    command: rsyslogd -n -f /etc/rsyslog.conf
    volumes:
      - ./rsyslog/conf/rsyslog.conf:/etc/rsyslog.conf
      - ./logs:/var/log/
    depends_on:
      - kafka
    ports:
      - "514:514"

  service-a:
    build: ./service-a
    environment:
      - SYSLOG_HOST=rsyslog
      - SYSLOG_PORT=514
    depends_on:
      - rsyslog

  service-b:
    build: ./service-b
    environment:
      - SYSLOG_HOST=rsyslog
      - SYSLOG_PORT=514
    depends_on:
      - rsyslog

  service-dumb:
    build: ./service-dumb
    depends_on:
      - rsyslog

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: EXTERNAL://:29092,INTERNAL://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./create-topics.sh:/usr/bin/create-topics.sh
    command:
      - sh
      - -c
      - |
        /etc/confluent/docker/run &
        sleep 10
        /usr/bin/create-topics.sh
        wait